### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by gbolo** [thomasDOTde/PowerDNS-Admin#17]
Great work on this fork! You picked up the slack on this project quite well. Looking into building a new docker image, would like to know if a new release is in order since master is already ahead 42 commits since last release tagged: `2017.11.02`

**Comment by thomasDOTwtf** [comment]
Hey, sorry for the late reply. I've been on holiday for some time.
I'd like to integrate the crypt option for SAML tokens before doing a new release.

**Comment by thomasDOTwtf** [comment]
Just created a new release after finishing SAML certificate handling.

**Comment by thomasDOTwtf** [comment]
I close the issue as there is a new release out.
