### ISSUE TITLE
Reverse Proxy Login/Logout

### ISSUE THREAD

**Issue by p-rintz** [thomasDOTde/PowerDNS-Admin#20]
Hi,

I am having a bit of a strange problem of which I am not sure whether it is a result of misconfiguration or if its a bug.

I have a user created and login through the built-in webserver is possible.

But as soon as I use a reverse proxy to 127.0.0.1:9393 (apache2 or caddy, both) the login is broken and the server automatically logs me into my user. A logout is impossible and just redirects to the Dashboard.

Logs simply show this when I click on logout:

```
[INFO] User "test" logged in successfully
[INFO]  192.168.43.2 - - [29/Jan/2018 21:17:42] "GET /logout HTTP/1.1" 302 -
[INFO] User "test" logged in successfully
[INFO] 192.168.43.2 - - [29/Jan/2018 21:17:43] "GET /login HTTP/1.1" 302 -
[INFO]  192.168.43.2 - - [29/Jan/2018 21:17:43] "GET /dashboard HTTP/1.1" 200 -
[INFO]  192.168.43.2 - - [29/Jan/2018 21:17:43] "GET /static/adminlte2/plugins/iCheck/all.css HTTP/1.1" 200 -
```

Thanks for your help.

**Comment by thomasDOTwtf** [comment]
Which kind of authentication are you using?

**Comment by p-rintz** [comment]
Just the basic auth.

**Comment by thomasDOTwtf** [comment]
Could you check the installed cookies before and after logout?
Might you be able to capture the HTTP response to logout?

**Comment by p-rintz** [comment]
I did a few more checks. I dont know how/why, but using the basic auth feature of the server also authenticates me in the auth portion of PowerDNS-Admin. If I disable basic auth in the web server the login screen of PDNS-Admin does in fact appear.

The logout still does not seem to work though even then. 

The following happens when the logout button is pressed:

```
GET https://192.168.43.2/logout HTTP/1.1
Host: 192.168.43.2
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://192.168.43.2/dashboard
Cookie: session=sessionID
DNT: 1
Authorization: Basic EncodedPasswordstring
Connection: keep-alive
Upgrade-Insecure-Requests: 1
```


Immediately followed by:

```
GET https://192.168.43.2/login HTTP/1.1
Host: 192.168.43.2
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://192.168.43.2/dashboard
Cookie: session=differentSessionID
DNT: 1
Authorization: Basic encodedPassword
Connection: keep-alive
Upgrade-Insecure-Requests: 1
```

**Comment by thomasDOTwtf** [comment]
Seems that your browser is sending BASIC-Authentication headers.
That will keep you logged in until you close and reopen the browser.

**Comment by thomasDOTwtf** [comment]
@p-rintz could you confirm that you received a BASIC auth request visiting the page firsttime?

**Comment by p-rintz** [comment]
@thomasDOTde I cannot be sure anymore. I would guess so off the top of my head. I will close this until I have some more time to test this.
